### PR TITLE
Fix ./scripts/lsync.sh script not getting EN_VERSION variable correctly

### LINKED ISSUE #34633: ./scripts/lsync.sh cannot sync files under zh-cn correctly.
**This is a Bug Report**
./scripts/lsync.sh cannot sync files under `zh-cn` correctly.

This problem should exist with  $LOCALIZED more than 2 characters.

** When happened
when zh -> zh-cn
see https://github.com/kubernetes/website/pull/34215

**Proposed Solution:**
`./scripts/lsync.sh` needs to be updated

```
EN_VERSION=`echo $LOCALIZED | sed "s/content\/..\//content\/en\//g"`
```
to
```
EN_VERSION=`echo $LOCALIZED | sed "s/content\/.\{2,5\}\//content\/en\//g"`
```

/cc @temnqm @howieyuen 
/language zh

### PR DESCRIPTION
**Pull request by mengjiao-liu**
Fixes #34633

### CODE REVIEW

**Comment by mengjiao-liu** [comment]
test command
```
./scripts/lsync.sh content/zh-cn/examples/controllers/job.yaml
```
output
```diff
diff --git a/content/en/examples/controllers/job.yaml b/content/en/examples/controllers/job.yaml
index b448f2eb81..a6e40bc778 100644
--- a/content/en/examples/controllers/job.yaml
+++ b/content/en/examples/controllers/job.yaml
@@ -7,7 +7,7 @@ spec:
     spec:
       containers:
       - name: pi
-        image: perl
+        image: perl:5.34
         command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
       restartPolicy: Never
   backoffLimit: 4

```

But there is no way to correctly check the directory
```
 ./scripts/lsync.sh content/zh-cn/examples/controllers/...
Path not found: 'content/zh-cn/examples/controllers/...'
```
I'll test and modify it again.

**Comment by mengjiao-liu** [comment]
>there is no way to correctly check the directory.

I read the  `scripts/lsync.sh` script code:
- Batch files sync scan only for directories where .md files exist, excluding yaml files.
https://github.com/kubernetes/website/blob/fc45c356955842603522481058e049c9fca5a57d/scripts/lsync.sh#L22

We can see that the script syncs the directory successfully.
```bash
./scripts/lsync.sh content/zh-cn/docs/
1       1       content/en/docs/tasks/run-application/force-delete-stateful-set-pod.md
1       2       content/en/docs/tasks/tools/install-kubectl-linux.md
1       1       content/en/docs/tasks/configure-pod-container/migrate-from-psp.md
49      44      content/en/docs/tasks/configure-pod-container/share-process-namespace.md
100     13      content/en/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
1       1       content/en/docs/tasks/administer-cluster/migrating-from-dockershim/_index.md
...
```

**Comment by Sea-n** [comment]
Code-wise looks good to me.

Don't put any language labels in global PR like this, some reviewers may skip it because of `lang/zh` label.

File: scripts/lsync.sh [hunk 1]
```diff
@@ -20,7 +20,7 @@ fi
 if [ -d "$1" ] ; then
   SYNCED=1
   for f in `find $1 -name "*.md"` ; do
-    EN_VERSION=`echo $f | sed "s/content\/..\//content\/en\//g"`
+    EN_VERSION=`echo $f | sed "s/content\/.\{2,5\}\//content\/en\//g"`
```
Comment (Sea-n) [inline scripts/lsync.sh:23]: I would more prefer this version:
```suggestion
    EN_VERSION=`echo $f | sed 's#content/[^/]*/#content/en/#'`
```

- Change delimiter to `#` to prevent escaping `/` in path.
- In this context, no need to use `"double quote"`.
- The string should only appeared at most once, so remove `/g` (global).
- Use `[^/]` (not slash) instead of `.` (any char).
- We can make sure find result would not have continuous `//`, so `*` instead of `{2,5}` or `+` should be fine.
